export enum BookingType {
    PT_SESSION = 'PT_SESSION',
    GROUP_SESSION = 'GROUP_SESSION',
}

export enum BookingStatus {
    SCHEDULED = 'SCHEDULED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    NO_SHOW = 'NO_SHOW',
}

export enum ConflictType {
    TRAINER_DOUBLE_BOOKED = 'TRAINER_DOUBLE_BOOKED',
    OUTSIDE_AVAILABILITY = 'OUTSIDE_AVAILABILITY',
    BLOCKED_OVERRIDE = 'BLOCKED_OVERRIDE',
}

export const BOOKING_ERRORS = {
    NOT_FOUND: 'BOOKING_NOT_FOUND',
    TRAINER_UNAVAILABLE: 'TRAINER_UNAVAILABLE',
    CONFLICT: 'BOOKING_CONFLICT',
    CONFLICT_DETAIL: 'BOOKING_CONFLICT_DETAIL',
    INSUFFICIENT_SESSIONS: 'INSUFFICIENT_SESSIONS',
    INVALID_DURATION: 'INVALID_DURATION',
    PAST_DATE: 'PAST_DATE',
    CANCEL_WINDOW_EXCEEDED: 'CANCEL_WINDOW_EXCEEDED',
} as const;
