export enum BookingType {
    PT_SESSION = 'PT_SESSION',
    GROUP_SESSION = 'GROUP_SESSION',
}

export enum BookingStatus {
    SCHEDULED = 'SCHEDULED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    NO_SHOW = 'NO_SHOW',
}

export enum ConflictType {
    TRAINER_DOUBLE_BOOKED = 'TRAINER_DOUBLE_BOOKED',
    OUTSIDE_AVAILABILITY = 'OUTSIDE_AVAILABILITY',
    BLOCKED_OVERRIDE = 'BLOCKED_OVERRIDE',
}

